### ISSUE TITLE
Flight paths (tracks) not working

### ISSUE THREAD

**Issue by tpatja** [Meisterschueler/ogn-viewer-android#38]
The flight paths have not been working again for the past few days, regardless of type. Could be the same backend problem in issue #37.. can you try restarting it again, please?

Thanks.

_Originally posted by @tpatja in https://github.com/Meisterschueler/ogn-viewer-android/issues/37#issuecomment-1586884171_

**Comment by prikril** [comment]
Hi @tpatja 
thanks for the info! I checked the server logs.
The backend was working until yesterday morning (2023-06-11 06:49 German time).
This time it was another reason: The server was rebooted and the backend didn't start automatically.
It is running again since today 2023-06-12 17:00 German time.

**Comment by tpatja** [comment]
I confirm the tracks are working again now. Thanks for the quick fix!
